### ISSUE TITLE
More general references in datacite.yml

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gogs#24]
The `references` field in the datacite file should be more general with respect to the reference ID.
```yaml
references:
    - 
       id: "xxxxxx"
       reftype: "IsSupplementTo"
       description: "Publication name or description"
```
The explanation text should explain that ID could be a DOI, URL, ISBN, arXiv, or PMID. They should be provided in the form `type:ID` e.g., `doi:10.xxx/zzzz`, `pmid:xxxyyy`, etc.

Update the validator in G-Node/gin-doi to accept this form.
